feat: разработать контроллеры
KhorkovRoman/java-shareit pull request #1
Opened 2022-08-18 20:25 UTC by KhorkovRoman

2022-08-19 22:29 UTC, Fleaman777 requested changes

2022-08-19 22:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    BookingStatus status;
поля должнв бвть private

2022-08-19 22:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    ItemDto createItem(@RequestHeader("X-Sharer-User-Id") Integer userId,
"X-Sharer-User-Id" можно вынести в константу и использовать ее в других методах

2022-08-19 22:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/ErrorHandler.java
> +package ru.practicum.shareit;
общие классы для всех сущностей можно вынести в пекедж common

2022-08-19 22:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  package ru.practicum.shareit.item;
сразу можно добавить подпакеты controller, service и тд

2022-08-19 22:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    public void validateUser(User owner, Integer userId) {
здорово что вынес валидацию в отдельные методы

2022-08-19 22:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                    .collect(Collectors.toList());
отличный получился стрим

2022-08-19 22:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemStorageInMemory.java
> +    Map<Integer, Item> itemMap = new HashMap<>();
поле должно быть private

в аналагичных местах так же

2022-08-19 22:29 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +        return usersDto;
хороший кандидат на стрим

2022-08-20 09:58 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    BookingStatus status;
сделал

2022-08-20 09:58 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    ItemDto createItem(@RequestHeader("X-Sharer-User-Id") Integer userId,
сделал

2022-08-20 09:59 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/ErrorHandler.java
> +package ru.practicum.shareit;
сделал

2022-08-20 10:04 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  package ru.practicum.shareit.item;
сделал

2022-08-20 10:06 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/item/ItemStorageInMemory.java
> +    Map<Integer, Item> itemMap = new HashMap<>();
сделал

2022-08-20 17:27 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    public void validateUser(User owner, Integer userId) {
ок

2022-08-20 17:27 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                    .collect(Collectors.toList());
ок

2022-08-20 17:28 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +        return usersDto;
сделал, и ItemMapper тоже сделал

2022-08-21 20:09 UTC, Fleaman777 approved these changes

2022-08-21 20:09 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private static final String USERID = "X-Sharer-User-Id";
может чуть более подходящее название было бы USER_ID_HEADER

2022-08-25 16:16 UTC, merged