Add bookings
KhorkovRoman/java-shareit pull request #2
Opened 2022-09-10 18:25 UTC by KhorkovRoman

2022-09-12 14:35 UTC, Fleaman777 requested changes

2022-09-12 14:35 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    BookingDto createBooking(@RequestHeader(USER_ID_HEADER) Long userId,
нужно добавить модификатор доступа, 
в др.  местах аналагично

2022-09-12 14:35 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public static State setState(String stateText) {
эту логику хорошо было бы вынести в класс State, 
т.к. в теории она может нам понадобится из ругих мест, не только из этого контроллера

и глагол set, здесь не очень подходит, т.к. метод ничего не просечивает

2022-09-12 14:35 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +                booking.getBooker().getId()
когда нужно просетать много полей в 1 объект, грамотней использовать builder

2022-09-12 14:35 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    public Long generateBookingId() {
больше похоже, что это вспомогательный метод, 
поэтому лучше его сдеоать private и перенести блие к концу класса

2022-09-12 14:35 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        }
попробуй немного переделать if условия, когда их много и они вложены др в друга, ухудшается восприятие кода, 

например некоторые условия можно сделать наоборот, например 
....
```
if (!Objects.equals(item.getOwner().getId(), ownerId)) {
throw new ValidationException(HttpStatus.NOT_FOUND,
                "Пользователь с id " + ownerId + " не является хозяином вещи.");
}
```
.....

в таком случае нам не нужно будет много логики обарачивать в условие if(Objects.equals(item.getOwner().getId(), ownerId)) {....}
и т.д.

2022-09-12 14:35 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    }
или можешь попробовать логику этого метода сделать через switch-case

2022-09-12 14:35 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public Long generateUserId() {
здесь тоже можно метод сделать private

2022-09-12 14:35 UTC, Fleaman777 commented on src/main/resources/schema.sql
> +    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
можно еще было бы добавить значение по умолчанию "текущую дату"

2022-09-12 16:03 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    BookingDto createBooking(@RequestHeader(USER_ID_HEADER) Long userId,
поставил модификатор public для методов BookingController, UserController, ItemController

2022-09-12 16:06 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    public Long generateBookingId() {
сразу под этим методом идет метод createBooking,  в котором и пременяется этот метод, генерация id букинга, больше он  нигде не применяется. Я думаю, не имеет смысла его ставить ближе к концу, так снизится читабельность кода. А модификатор private я поставил

2022-09-12 16:08 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    public Long generateUserId() {
установил private, здесь тоже не надо переносить метод в конец, это снизит читабельность

2022-09-12 16:16 UTC, KhorkovRoman commented on src/main/resources/schema.sql
> +    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
добавил DEFAULT CURRENT_TIMESTAMP для поля star_date

2022-09-12 16:22 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public static State setState(String stateText) {
метод вынес в enum BookingStatus, название метода изменил на findState, в методах вызываю State state = BookingStatus.findState(stateText);

2022-09-12 17:24 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        }
вынес код из if, как тут указано....

2022-09-12 17:24 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    }
я сделал, по совету выше

2022-09-12 18:03 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +                booking.getBooker().getId()
изменил: я использовал аннотацию @Builder и создаю объекты в мапперах booking, item, user

2022-09-13 15:33 UTC, Fleaman777 approved these changes

2022-09-13 15:33 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +                .build();
отлично, то, что нужно

2022-09-13 15:33 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        }
здорово, 
стало ощутимо лучше

2022-09-13 15:58 UTC, merged