feat: добавить тесты
KhorkovRoman/java-shareit pull request #3
Opened 2022-10-05 17:17 UTC by KhorkovRoman

2022-10-06 17:40 UTC, Fleaman777 requested changes

2022-10-06 17:40 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                           @Positive @RequestParam(name = "size", defaultValue = "20") Integer size) {
если название параметра name совпадает с названием аргумента, то name можно не указывать

относится ко всем похожим местам

2022-10-06 17:40 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        final PageRequest pageRequest = PageRequest.of(page, size);
логику с расчетом получением PageRequest можно было бы вынести в отдельный метод

2022-10-06 17:40 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public void validateParam(Integer from, Integer size) {
грамотное вынесение валидации в отдельный метод

2022-10-06 17:40 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/requests/model/ItemRequest.java
> +@Setter
проверь что входит в аннотацию @Data, 
вроде как в нее уже включены геттеры, сетторы и др. аннотации

2022-10-06 17:40 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestService.java
> +    public Long generateItemRequestId() {
этот метод используется только внутри ItemRequestService, поэтому его можно сделать private, и переместить в конец класса

2022-10-06 17:40 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    BookingController bookingController;
в тестах тоже нужно придерживаться принципа инкапсуляции,

относится ко всем подобным моментам в тестах

2022-10-06 17:40 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", user.getId()))
формирование контента, можно вынести в отдельный общий вспомогательный метод

2022-10-06 17:40 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +        assertEquals(timeStartBooking1, booking.getStart());
попробуй общую часть ассершинов вынести в отдельный метод, можно с аргументами, что бы этот метод подходил к большему количеству тест методов

2022-10-06 17:40 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +                        .header("X-Sharer-User-Id", user.getId()))
здесь тоже общую часть можно было бы попробовать вынести в отдельный метод

2022-10-06 17:40 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/user/controller/UserControllerTest.java
> +    void getUserById() throws Exception {
тест методы лучше называть немного по другому, чем методы тестируемых сервисов, так, если что, будет проще искать по всему приложению необходимые методы

самое просто просто добавить слово test в начале названия,
в идеале добавлять в название условаие при котором выполняется тест, например
getUserByIdIfIdIsNull

2022-10-08 18:28 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        final PageRequest pageRequest = PageRequest.of(page, size);
вынес в отдельный метод в классах BookingController, ItemController, ItemRequestController... в UserController pageRequest не используется

2022-10-08 18:28 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public void validateParam(Integer from, Integer size) {
ок

2022-10-08 18:37 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/requests/model/ItemRequest.java
> +@Setter
@Data содержит @ToString, @EqualsAndHashCode, @Getter, @Setter, @RequiredArgsConstructor.... убрал лишние аннотации во всех классах моделей

2022-10-08 18:40 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/requests/service/ItemRequestService.java
> +    public Long generateItemRequestId() {
сделал private, переместил в конец класса

2022-10-08 19:16 UTC, KhorkovRoman commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +    BookingController bookingController;
для всех полей тестовых классов указал private

2022-10-08 20:11 UTC, KhorkovRoman commented on src/test/java/ru/practicum/shareit/user/controller/UserControllerTest.java
> +    void getUserById() throws Exception {
в названии всех тестовых методов добавил в начале test, например testGetBookingsByOwner()

2022-10-08 21:23 UTC, KhorkovRoman commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +        assertEquals(timeStartBooking1, booking.getStart());
вынес ассершины в отдельный тест assertCommonTest() с аргументами, подходит для большинства тестов

2022-10-08 21:33 UTC, KhorkovRoman commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                           @Positive @RequestParam(name = "size", defaultValue = "20") Integer size) {
убрал name, где аргумент совпадает с параметром name.... убрал в классах BookingController, ItemController, ItemRequestController

2022-10-08 22:40 UTC, KhorkovRoman commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", user.getId()))
вынес в отдельный класс public MockHttpServletRequestBuilder mockAction(MockHttpServletRequestBuilder mockMvc, Long userId, Item item)

2022-10-08 22:50 UTC, KhorkovRoman commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +                        .header("X-Sharer-User-Id", user.getId()))
здесь также вынес в отдельный класс public MockHttpServletRequestBuilder mockAction(MockHttpServletRequestBuilder mockMvc, Long userId, BookingDtoIn bookingDtoIn)

2022-10-10 07:16 UTC, Fleaman777 approved these changes

2022-10-10 07:16 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +    public MockHttpServletRequestBuilder mockAction(MockHttpServletRequestBuilder mockMvc, Long userId, Item item)
отлично, это то, что я и хотел увидеть :)

но если что, модификатор можно использовать private, т.к. это метод используется только внутри этого класса

2022-10-10 07:49 UTC, merged