feat: разбить на микросервисы
KhorkovRoman/java-shareit pull request #4
Opened 2022-10-17 18:30 UTC by KhorkovRoman

2022-10-25 19:30 UTC, db-exp requested changes

2022-10-25 19:30 UTC, db-exp commented on pom.xml
> +    <parent>
parent должен быть наверху сразу после model

2022-10-25 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +	private Long itemId;
Лучше добавить nonnull и min

2022-10-25 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +								                @PathVariable Long bookingId,
есть смысл добавить валидацию на  min max

2022-10-25 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +											 @PathVariable Long bookingId) {
есть смысл добавить валидацию на min max

2022-10-25 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  public class ItemDto {
Для String полей нужно добавить size/null или notnull

2022-10-25 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                              @PathVariable Long itemId) {
Нужно добавить валидацию min/max

2022-10-25 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                             @PathVariable Long itemId,
Нужно добавить валидацию min/max

2022-10-25 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                           @PathVariable Long itemId) {
Нужно добавить валидацию min/max

2022-10-25 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/requests/ItemRequestController.java
> +                                                     @PathVariable Long requestId) {
Нужно добавить валидацию min/max

2022-10-25 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/requests/dto/ItemRequestDtoIn.java
>  public class ItemRequestDtoIn {
Нужна валидация на размер String поля

2022-10-25 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/requests/ItemRequestController.java
> +    public void validateParam(Integer from, Integer size) {
Можно вынести в класс-утилиту - во всех контроллерах повторяется

2022-10-25 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/requests/dto/ItemRequestDto.java
>      private LocalDateTime created;
Нужно добавить валидацию на время

2022-10-25 19:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/requests/dto/ItemRequestDto.java
>      private String description;
Нужно добавить валидацию на размер

2022-10-25 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/booking/dto/BookingDtoItem.java
> +public class BookingDtoItem {
На сервере валидация по заданию не нужна, только на gateway

2022-10-25 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +                //.itemId(booking.getItem().getId())
Закоментированный код лучше удалить

2022-10-25 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +                //.itemId(booking.getItem().getId())
Закоментированный код лучше удалить

2022-10-25 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/common/ErrorHandler.java
> +public class ErrorHandler {
На сервере валидация по заданию не нужна, только на gateway, соответственно и bad request тут быть не может

2022-10-25 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>          user.setId(generateUserId());
В модели стоит    @GeneratedValue(strategy = GenerationType.IDENTITY), то есть специально проставлять Id не нужно

2022-10-25 19:30 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/user/controller/UserController.java
На сервере для единобразного подхода лучше убрать Valid из контроллеров, ну или везде оставить)

2022-10-25 20:06 UTC, KhorkovRoman commented on pom.xml
> +    <parent>
сделал

2022-10-25 20:08 UTC, KhorkovRoman commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookItemRequestDto.java
> +	private Long itemId;
сделал

2022-10-25 20:10 UTC, KhorkovRoman commented on gateway/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  public class ItemDto {
для String полей стоит аннотация @NotBlank, кто-то мне говорил, что @NotNull для String полей некорректно

2022-10-25 20:11 UTC, KhorkovRoman commented on server/src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +                //.itemId(booking.getItem().getId())
удалил

2022-10-25 20:12 UTC, KhorkovRoman commented on server/src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +                //.itemId(booking.getItem().getId())
удалил

2022-10-25 20:16 UTC, KhorkovRoman commented on server/src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>          user.setId(generateUserId());
убрал setId()

2022-10-25 20:18 UTC, KhorkovRoman commented on server/src/main/java/ru/practicum/shareit/user/controller/UserController.java
убрал Valid из контроллеров

2022-10-25 20:20 UTC, KhorkovRoman commented on server/src/main/java/ru/practicum/shareit/common/ErrorHandler.java
> +public class ErrorHandler {
удалил класс из server

2022-10-25 20:46 UTC, KhorkovRoman commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +								                @PathVariable Long bookingId,
добавил валидацию @Min(1) @Max(1000000) Long ownerId

2022-10-25 20:46 UTC, KhorkovRoman commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +											 @PathVariable Long bookingId) {
добавил валидацию @min(1) @max(1000000) Long userId

2022-10-26 06:46 UTC, db-exp requested changes

2022-10-26 06:46 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/requests/ItemRequestController.java
> +    public void validateParam(Integer from, Integer size) {
Давай вынесем?

2022-10-26 18:26 UTC, db-exp approved these changes

2022-10-27 07:55 UTC, merged